# Generated by Django 4.1.5 on 2023-01-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otazka',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='otazka',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='otazka',
            name='c_id',
        ),
    ]
