# Generated by Django 4.1.5 on 2023-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_otazka_a_id_remove_otazka_b_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
