# Generated by Django 4.1.5 on 2023-01-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_odpoved_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otazka',
            name='odpoved_c',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
