# Generated by Django 4.1.5 on 2023-01-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_otazka_odpoved_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='otazka',
            name='skore',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otazka',
            name='otazka',
            field=models.TextField(max_length=250),
        ),
    ]
