# Generated by Django 4.1.5 on 2023-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otazka_skore_alter_otazka_otazka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=41)),
                ('zkraceny_nazev', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='otazka',
            name='odpoved_a',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='otazka',
            name='otazka',
            field=models.TextField(max_length=270),
        ),
    ]
